sudo: required
services:
    - docker

before_install:
    - docker build -t akshaylokur/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true akshaylokur/react-test npm test

after_success:
    # Build production images
    - docker build -t akshaylokur/multi-container-client ./client
    - docker build -t akshaylokur/multi-container-server ./server
    - docker build -t akshaylokur/multi-container-nginx ./nginx
    - docker build -t akshaylokur/multi-container-worker ./worker

    # Login to docker hub from CLI
    - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin

    # Push images to Docker Hub
    - docker push akshaylokur/multi-container-client
    - docker push akshaylokur/multi-container-server
    - docker push akshaylokur/multi-container-nginx
    - docker push akshaylokur/multi-container-worker

deploy:
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: multi-docker
    env: MultiDocker-env
    bucket-name: elasticbeanstalk-ap-southeast-1-113111868177
    bucket-path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY




